// Language Context — Multilingual i18n System
import React, { createContext, useContext, useEffect, useState, useCallback } from 'react';
import storageService, { KEYS } from '../services/storage';

// ─── Available Languages ──────────────────────────────────────
export const LANGUAGES = [
  { code: 'hi', name: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' },
  { code: 'en', name: 'English', native: 'English', flag: '🇬🇧' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', native: 'मराठी', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം', flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'or', name: 'Odia', native: 'ଓଡ଼ିଆ', flag: '🇮🇳' },
  { code: 'ur', name: 'Urdu', native: 'اردو', flag: '🇵🇰' },
];

interface LanguageContextType {
  language: string;
  setLanguage: (code: string) => Promise<void>;
  t: (key: string, fallback?: string) => string;
  tWithVars: (key: string, vars: Record<string, string | number>, fallback?: string) => string;
  getCurrentLanguage: () => { code: string; name: string; native: string; flag: string };
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export const useTranslation = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    return {
      language: 'hi',
      t: (key: string, fallback?: string) => fallback || key,
      tWithVars: (key: string, vars: Record<string, string | number>, fallback?: string) => fallback || key,
      getCurrentLanguage: () => ({ code: 'hi', name: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' }),
      isRTL: false,
      setLanguage: async () => {},
    };
  }
  return ctx;
};

export const useLanguage = useTranslation;

// ─── Translations ─────────────────────────────────────────────
// Compact dictionary for all screens. Supports English + Hindi + fallback to English.

interface TranslationsDict {
  [key: string]: string | TranslationsDict | TranslationsDict[];
}

const en: TranslationsDict = {
  app: {
    name: 'Krishi Sahayak',
    tagline: 'Smart Farming Assistant',
    taglineHi: 'स्मार्ट कृषि सहायक',
    version: '2.0.0',
  },
  nav: {
    home: 'Home',
    weather: 'Weather',
    market: 'Market',
    crops: 'Crops',
    more: 'More',
    aiAssistant: 'AI Assistant',
    diseaseDetection: 'Disease Detection',
    community: 'Community Feed',
    groups: 'Farmer Groups',
    messages: 'Messages',
    polls: 'Polls',
    notifications: 'Notifications',
    schemes: 'Govt Schemes',
    soilTesting: 'Soil Testing',
    cropCalendar: 'Crop Calendar',
    cropGuide: 'Crop Guide',
    loanCalc: 'Loan Calculator',
    grievances: 'Grievances',
    dailyTrack: 'Daily Track',
    analytics: 'Analytics',
    profile: 'Profile',
    settings: 'Settings',
    about: 'About',
  },
  common: {
    loading: 'Loading...',
    error: 'Something went wrong',
    retry: 'Retry',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',
    filter: 'Filter',
    close: 'Close',
    confirm: 'Confirm',
    submit: 'Submit',
    refresh: 'Refresh',
    seeAll: 'See All',
    noData: 'No data available',
    comingSoon: 'Coming Soon',
    enabled: 'Enabled',
    disabled: 'Disabled',
    yes: 'Yes',
    no: 'No',
    or: 'OR',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    continue: 'Continue',
    start: 'Get Started',
  },
  onboarding: {
    skip: 'Skip',
    next: 'Next →',
    chooseLanguage: 'Choose Language →',
    getStarted: 'Get Started →',
    languageTitle: 'Choose Language',
    languageSubtitle: 'भाषा चुनें',
    languageChangeNote: 'You can change language anytime in Settings',
    slides: [
      {
        title: 'Krishi Sahayak',
        subtitle: 'स्मार्ट कृषि सहायक',
        desc: 'Your intelligent farming companion. Get real-time weather, market prices, crop advice, and government schemes in your preferred language.',
      },
      {
        title: 'Real-Time Weather',
        subtitle: 'मौसम अपडेट',
        desc: 'Accurate 7-day weather forecasts, rainfall predictions, and severe weather alerts tailored to your farm location.',
      },
      {
        title: 'Market Prices',
        subtitle: 'बाजार भाव',
        desc: 'Live mandi prices for crops in your area. Track price trends, compare across markets, and decide the best time to sell.',
      },
      {
        title: 'Disease Detection',
        subtitle: 'रोग पहचान',
        desc: 'Snap a photo of your crop and our AI instantly identifies diseases, pests, and nutrient deficiencies with treatment recommendations.',
      },
      {
        title: 'Government Schemes',
        subtitle: 'सरकारी योजनाएं',
        desc: 'Discover and apply for PM-KISAN, Fasal Bima Yojana, Soil Health Cards, and more. Get notified about new benefits.',
      },
    ],
  },
  auth: {
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Sign in to continue',
    registerTitle: 'Create Account',
    registerSubtitle: 'Join the farming community',
    forgotPassword: 'Forgot Password?',
    email: 'Email',
    emailPlaceholder: 'Enter your email',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    name: 'Full Name',
    namePlaceholder: 'Enter your full name',
    confirmPassword: 'Confirm Password',
    confirmPasswordPlaceholder: 'Re-enter your password',
    signIn: 'Sign In',
    signUp: 'Create Account',
    continueGoogle: 'Continue with Google',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    createAccount: 'Create Account',
    loginHere: 'Sign In',
    or: 'OR',
    resetSent: 'Reset link sent! Check your email.',
    sendReset: 'Send Reset Link',
    backToLogin: 'Back to Sign In',
    errors: {
      enterEmail: 'Please enter your email',
      enterPassword: 'Please enter your password',
      enterName: 'Please enter your name',
      passwordLength: 'Password must be at least 6 characters',
      passwordsMatch: 'Passwords do not match',
    },
  },
  home: {
    greeting: {
      morning: 'Good Morning',
      afternoon: 'Good Afternoon',
      evening: 'Good Evening',
    },
    todayWeather: "Today's Weather",
    quickActions: 'Quick Actions',
    marketPrices: 'Market Prices',
    stats: {
      temperature: 'Temp',
      humidity: 'Humidity',
      rainfall: 'Rainfall',
    },
    insights: 'Smart Insights',
    lastUpdated: 'Last updated',
    pullToRefresh: 'Pull to refresh',
  },
  profile: {
    title: 'Profile',
    subtitle: 'Your account',
    posts: 'Posts',
    helpful: 'Helpful',
    answers: 'Answers',
    questions: 'Questions',
    settings: 'Settings',
    language: 'Language',
    theme: 'Theme',
    notifications: 'Notifications',
    account: 'Account',
    changePassword: 'Change Password',
    emailVerification: 'Email Verification',
    verified: 'Verified',
    notVerified: 'Not Verified',
    privacyPolicy: 'Privacy Policy',
    termsConditions: 'Terms & Conditions',
    appInfo: 'App Info',
    version: 'Version',
    signOut: 'Sign Out',
    logoutConfirm: 'Are you sure you want to logout?',
    farmer: '👨‍🌾 Farmer',
    expert: '👨‍🔬 Agri Expert',
  },
  settings: {
    title: 'Settings',
    language: 'App Language',
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    notifications: 'Notifications',
    weatherAlerts: 'Weather Alerts',
    priceAlerts: 'Price Alerts',
    schemeAlerts: 'Scheme Alerts',
    diseaseAlerts: 'Disease Alerts',
    communityAlerts: 'Community Alerts',
    about: 'About',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
  },
  weather: {
    title: 'Weather',
    today: "Today's Weather",
    forecast: '7-Day Forecast',
    hourly: 'Hourly',
    feelsLike: 'Feels Like',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    humidity: 'Humidity',
    wind: 'Wind',
    rainfall: 'Rainfall',
    uvIndex: 'UV Index',
    pressure: 'Pressure',
    dewPoint: 'Dew Point',
    visibility: 'Visibility',
    airQuality: 'Air Quality',
    alerts: 'Weather Alerts',
    recommendations: 'Farming Recommendations',
    live: 'LIVE',
    lastUpdated: 'Last updated',
    noData: 'No weather data available',
  },
  market: {
    title: 'Market Prices',
    alerts: 'Price Alerts',
    setAlert: 'Set Price Alert',
    commodity: 'Commodity',
    price: 'Price',
    trend: 'Trend',
    market: 'Market',
    state: 'State',
    quantity: 'Qt.',
    noData: 'No market data available',
    alertWhen: 'Alert when price',
    goesAbove: 'goes above',
    goesBelow: 'goes below',
    addAlert: 'Add Alert',
    activeAlerts: 'Active Alerts',
    alertHistory: 'Alert History',
    noAlerts: 'No alerts set',
    acknowledge: 'Acknowledge',
  },
  crop: {
    title: 'Crop Info',
    search: 'Search crops...',
    season: 'Season',
    soilType: 'Soil Type',
    duration: 'Duration',
    temperature: 'Temperature',
    rainfall: 'Rainfall',
    varieties: 'Varieties',
    practices: 'Best Practices',
    noData: 'No crops found',
  },
  disease: {
    title: 'Disease Detection',
    upload: 'Upload Photo',
    analyze: 'Analyze',
    analyzing: 'Analyzing...',
    results: 'Results',
    symptoms: 'Symptoms',
    causes: 'Causes',
    treatment: 'Treatment',
    prevention: 'Prevention',
    confidence: 'Confidence',
    severity: 'Severity',
    noPhoto: 'Take or select a photo to begin',
  },
  community: {
    title: 'Community Feed',
    newPost: 'New Post',
    replies: 'Replies',
    reply: 'Reply',
    writeReply: 'Write your reply...',
    solved: 'Solved',
    markSolved: 'Mark Solved',
    delete: 'Delete',
    search: 'Search posts...',
    category: 'Category',
    urgency: 'Urgency',
    noPosts: 'No posts yet',
    beFirst: 'Be the first to post!',
  },
  schemes: {
    title: 'Government Schemes',
    search: 'Search schemes...',
    category: 'Category',
    benefits: 'Benefits',
    eligibility: 'Eligibility',
    documents: 'Documents Required',
    apply: 'Application Process',
    website: 'Official Website',
    helpline: 'Helpline',
    noData: 'No schemes found',
  },
  soil: {
    title: 'Soil Testing',
    newTest: 'New Test',
    ph: 'pH Level',
    nitrogen: 'Nitrogen (N)',
    phosphorus: 'Phosphorus (P)',
    potassium: 'Potassium (K)',
    organicCarbon: 'Organic Carbon',
    health: 'Soil Health',
    recommendations: 'Recommendations',
    history: 'Test History',
    noTests: 'No tests yet',
    optimal: 'Optimal',
    low: 'Low',
    high: 'High',
    excellent: 'Excellent',
    good: 'Good',
    needsImprovement: 'Needs Improvement',
  },
  calendar: {
    title: 'Crop Calendar',
    today: 'Today',
    month: 'Month',
    addEvent: 'Add Event',
    editEvent: 'Edit Event',
    activity: 'Activity',
    crop: 'Crop',
    date: 'Date',
    status: 'Status',
    done: 'Done',
    pending: 'Pending',
    missed: 'Missed',
    noEvents: 'No events planned',
  },
  schemesData: {
    pmKisan: {
      name: 'PM-KISAN',
      ministry: 'Ministry of Agriculture',
      benefit: '₹6,000/year income support to farmer families',
      eligibility: 'All landholding farmer families',
      docs: 'Aadhaar Card, Land Records, Bank Account',
    },
    soilHealth: {
      name: 'Soil Health Card Scheme',
      ministry: 'Ministry of Agriculture',
      benefit: 'Free soil testing & nutrient recommendations',
      eligibility: 'All farmers',
      docs: 'Land records, Farmer ID',
    },
    pmfby: {
      name: 'PM Fasal Bima Yojana',
      ministry: 'Ministry of Agriculture',
      benefit: 'Crop insurance with low premium',
      eligibility: 'All farmers growing notified crops',
      docs: 'Land records, Bank details, Crop details',
    },
    kcc: {
      name: 'Kisan Credit Card',
      ministry: 'Ministry of Finance',
      benefit: 'Short-term crop loans up to ₹3 lakh at 4% interest',
      eligibility: 'All farmers, sharecroppers, tenant farmers',
      docs: 'Land records, Identity proof, Passport photo',
    },
    pmfme: {
      name: 'PM Formalisation of Micro Food Processing',
      ministry: 'Ministry of Food Processing',
      benefit: 'Credit-linked subsidy up to ₹10 lakh',
      eligibility: 'Individual farmers, SHGs, FPOs',
      docs: 'Project report, Identity proof, Bank details',
    },
  },
  groups: {
    title: 'Farmer Groups',
    search: 'Search groups...',
    create: 'Create Group',
    join: 'Join',
    leave: 'Leave',
    members: 'Members',
    posts: 'Posts',
    category: 'Category',
    noGroups: 'No groups found',
    createFirst: 'Create the first group!',
  },
  messages: {
    title: 'Messages',
    noConversations: 'No conversations yet',
    noMessages: 'No messages yet',
    typePlaceholder: 'Type a message...',
    online: 'Online',
    offline: 'Offline',
  },
  notifications: {
    title: 'Notifications',
    markAllRead: 'Mark All Read',
    noNotifications: 'No notifications yet',
    filter: {
      all: 'All',
      unread: 'Unread',
      read: 'Read',
    },
  },
  polls: {
    title: 'Polls',
    create: 'Create Poll',
    vote: 'Vote',
    votes: 'votes',
    noPolls: 'No active polls',
    remaining: 'remaining',
    category: 'Category',
  },
  loan: {
    title: 'Loan Calculator',
    amount: 'Loan Amount (₹)',
    rate: 'Interest Rate (%)',
    tenure: 'Tenure (months)',
    monthlyEMI: 'Monthly EMI',
    totalInterest: 'Total Interest',
    totalAmount: 'Total Amount',
    loanType: 'Loan Type',
    calculate: 'Calculate',
    types: {
      personal: 'Personal Loan',
      crop: 'Crop Loan',
      gold: 'Gold Loan',
      equipment: 'Equipment Loan',
    },
  },
  grievances: {
    title: 'Grievances',
    newGrievance: 'New Complaint',
    subject: 'Subject',
    description: 'Description',
    category: 'Category',
    status: 'Status',
    pending: 'Pending',
    resolved: 'Resolved',
    rejected: 'Rejected',
    inProgress: 'In Progress',
    noGrievances: 'No complaints filed',
    categories: {
      irrigation: 'Irrigation',
      seeds: 'Seeds',
      fertilizer: 'Fertilizer',
      subsidy: 'Subsidy',
      electricity: 'Electricity',
      road: 'Road Access',
      pricing: 'Pricing',
      compensation: 'Crop Compensation',
      other: 'Other',
    },
  },
  tracking: {
    title: 'Daily Tracking Log',
    addEntry: 'Add Entry',
    activity: 'Activity',
    notes: 'Notes',
    cropHealth: 'Crop Health',
    good: 'Good',
    average: 'Average',
    poor: 'Poor',
    noEntries: 'No entries yet',
    activities: {
      watering: 'Watering',
      fertilizing: 'Fertilizing',
      weeding: 'Weeding',
      spraying: 'Spraying',
      harvesting: 'Harvesting',
      planting: 'Planting',
      other: 'Other',
    },
  },
  analytics: {
    title: 'Analytics',
    totalEntries: 'Total Entries',
    activeCrops: 'Active Crops',
    completedTasks: 'Completed Tasks',
    weatherImpact: 'Weather Impact',
    insights: 'Smart Insights',
    noData: 'Not enough data for insights yet',
    recommendations: 'Recommendations',
    trends: 'Trends',
  },
  voice: {
    listening: 'Listening...',
    tapToSpeak: 'Tap to speak',
    processing: 'Processing...',
    notSupported: 'Voice is not supported on this device',
    permissionDenied: 'Microphone permission denied',
    error: 'Voice recognition error',
  },
};

// Hindi translations
const hi: TranslationsDict = {
  app: {
    name: 'कृषि सहायक',
    tagline: 'स्मार्ट कृषि सहायक',
    taglineEn: 'स्मार्ट फार्मिंग असिस्टेंट',
    version: '2.0.0',
  },
  nav: {
    home: 'होम',
    weather: 'मौसम',
    market: 'बाजार',
    crops: 'फसलें',
    more: 'और',
    aiAssistant: 'AI सहायक',
    diseaseDetection: 'रोग पहचान',
    community: 'समुदाय',
    groups: 'किसान समूह',
    messages: 'संदेश',
    polls: 'पोल',
    notifications: 'सूचनाएं',
    schemes: 'सरकारी योजनाएं',
    soilTesting: 'मिट्टी परीक्षण',
    cropCalendar: 'फसल कैलेंडर',
    cropGuide: 'फसल गाइड',
    loanCalc: 'ऋण कैलकुलेटर',
    grievances: 'शिकायतें',
    dailyTrack: 'दैनिक लॉग',
    analytics: 'विश्लेषण',
    profile: 'प्रोफाइल',
    settings: 'सेटिंग्स',
    about: 'हमारे बारे में',
  },
  common: {
    loading: 'लोड हो रहा है...',
    error: 'कुछ गलत हो गया',
    retry: 'पुनः प्रयास',
    save: 'सेव करें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    search: 'खोजें',
    filter: 'फिल्टर',
    close: 'बंद करें',
    confirm: 'पुष्टि करें',
    submit: 'सबमिट करें',
    refresh: 'रिफ्रेश',
    seeAll: 'सभी देखें',
    noData: 'कोई डेटा उपलब्ध नहीं',
    comingSoon: 'जल्द आ रहा है',
    enabled: 'सक्षम',
    disabled: 'अक्षम',
    yes: 'हां',
    no: 'नहीं',
    or: 'या',
    back: 'वापस',
    next: 'अगला',
    done: 'पूर्ण',
    continue: 'जारी रखें',
    start: 'शुरू करें',
  },
  onboarding: {
    skip: 'छोड़ें',
    next: 'अगला →',
    chooseLanguage: 'भाषा चुनें →',
    getStarted: 'शुरू करें →',
    languageTitle: 'भाषा चुनें',
    languageSubtitle: 'अपनी भाषा चुनें',
    languageChangeNote: 'आप सेटिंग्स में कभी भी भाषा बदल सकते हैं',
    slides: [
      {
        title: 'कृषि सहायक',
        subtitle: 'स्मार्ट कृषि सहायक',
        desc: 'आपका बुद्धिमान कृषि साथी। रियल-टाइम मौसम, बाजार भाव, फसल सलाह और सरकारी योजनाएं आपकी पसंदीदा भाषा में प्राप्त करें।',
      },
      {
        title: 'रियल-टाइम मौसम',
        subtitle: 'मौसम अपडेट',
        desc: 'आपके खेत के स्थान के अनुसार सटीक 7-दिन का मौसम पूर्वानुमान, वर्षा भविष्यवाणी और गंभीर मौसम चेतावनी।',
      },
      {
        title: 'बाजार भाव',
        subtitle: 'मंडी मूल्य',
        desc: 'आपके क्षेत्र की फसलों के लाइव मंडी मूल्य। मूल्य रुझान ट्रैक करें, बाजारों की तुलना करें और बेचने का सही समय तय करें।',
      },
      {
        title: 'रोग पहचान',
        subtitle: 'फसल रोग पहचान',
        desc: 'अपनी फसल की फोटो खींचें और हमारा AI तुरंत रोगों, कीटों और पोषक तत्वों की कमी की पहचान कर उपचार सुझाएगा।',
      },
      {
        title: 'सरकारी योजनाएं',
        subtitle: 'सरकारी योजनाएं',
        desc: 'PM-KISAN, फसल बीमा योजना, मृदा स्वास्थ्य कार्ड और अधिक योजनाओं की खोज करें। नए लाभों की सूचना प्राप्त करें।',
      },
    ],
  },
  auth: {
    loginTitle: 'आपका स्वागत है',
    loginSubtitle: 'जारी रखने के लिए साइन इन करें',
    registerTitle: 'खाता बनाएं',
    registerSubtitle: 'किसान समुदाय से जुड़ें',
    forgotPassword: 'पासवर्ड भूल गए?',
    email: 'ईमेल',
    emailPlaceholder: 'अपना ईमेल दर्ज करें',
    password: 'पासवर्ड',
    passwordPlaceholder: 'अपना पासवर्ड दर्ज करें',
    name: 'पूरा नाम',
    namePlaceholder: 'अपना पूरा नाम दर्ज करें',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    confirmPasswordPlaceholder: 'पासवर्ड फिर से दर्ज करें',
    signIn: 'साइन इन',
    signUp: 'खाता बनाएं',
    continueGoogle: 'Google से जारी रखें',
    noAccount: 'खाता नहीं है?',
    haveAccount: 'पहले से खाता है?',
    createAccount: 'खाता बनाएं',
    loginHere: 'साइन इन करें',
    or: 'या',
    resetSent: 'रीसेट लिंक भेजा गया! अपना ईमेल जांचें।',
    sendReset: 'रीसेट लिंक भेजें',
    backToLogin: 'साइन इन पर वापस',
    errors: {
      enterEmail: 'कृपया अपना ईमेल दर्ज करें',
      enterPassword: 'कृपया अपना पासवर्ड दर्ज करें',
      enterName: 'कृपया अपना नाम दर्ज करें',
      passwordLength: 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
      passwordsMatch: 'पासवर्ड मेल नहीं खाते',
    },
  },
  home: {
    greeting: {
      morning: 'सुप्रभात',
      afternoon: 'नमस्कार',
      evening: 'शुभ संध्या',
    },
    todayWeather: 'आज का मौसम',
    quickActions: 'त्वरित कार्य',
    marketPrices: 'बाजार भाव',
    stats: {
      temperature: 'तापमान',
      humidity: 'नमी',
      rainfall: 'वर्षा',
    },
    insights: 'स्मार्ट सुझाव',
    lastUpdated: 'अंतिम अपडेट',
    pullToRefresh: 'रिफ्रेश करें',
  },
  profile: {
    title: 'प्रोफाइल',
    subtitle: 'आपका खाता',
    posts: 'पोस्ट',
    helpful: 'उपयोगी',
    answers: 'जवाब',
    questions: 'प्रश्न',
    settings: 'सेटिंग्स',
    language: 'भाषा',
    theme: 'थीम',
    notifications: 'सूचनाएं',
    account: 'खाता',
    changePassword: 'पासवर्ड बदलें',
    emailVerification: 'ईमेल पुष्टि',
    verified: 'पुष्टि हुई',
    notVerified: 'पुष्टि नहीं हुई',
    privacyPolicy: 'गोपनीयता नीति',
    termsConditions: 'नियम व शर्तें',
    appInfo: 'ऐप जानकारी',
    version: 'संस्करण',
    signOut: 'साइन आउट',
    logoutConfirm: 'क्या आप वाकई साइन आउट करना चाहते हैं?',
    farmer: '👨‍🌾 किसान',
    expert: '👨‍🔬 कृषि विशेषज्ञ',
  },
  settings: {
    title: 'सेटिंग्स',
    language: 'ऐप भाषा',
    appearance: 'दृश्य',
    darkMode: 'डार्क मोड',
    notifications: 'सूचनाएं',
    weatherAlerts: 'मौसम चेतावनी',
    priceAlerts: 'मूल्य चेतावनी',
    schemeAlerts: 'योजना चेतावनी',
    diseaseAlerts: 'रोग चेतावनी',
    communityAlerts: 'समुदाय चेतावनी',
    about: 'हमारे बारे में',
    privacy: 'गोपनीयता नीति',
    terms: 'सेवा की शर्तें',
  },
  weather: {
    title: 'मौसम',
    today: 'आज का मौसम',
    forecast: '7-दिन का पूर्वानुमान',
    hourly: 'प्रति घंटा',
    feelsLike: 'महसूस होता है',
    sunrise: 'सूर्योदय',
    sunset: 'सूर्यास्त',
    humidity: 'नमी',
    wind: 'हवा',
    rainfall: 'वर्षा',
    uvIndex: 'UV सूचकांक',
    pressure: 'दबाव',
    dewPoint: 'ओस बिंदु',
    visibility: 'दृश्यता',
    airQuality: 'वायु गुणवत्ता',
    alerts: 'मौसम चेतावनी',
    recommendations: 'कृषि सुझाव',
    live: 'लाइव',
    lastUpdated: 'अंतिम अपडेट',
    noData: 'मौसम डेटा उपलब्ध नहीं',
  },
  market: {
    title: 'बाजार भाव',
    alerts: 'मूल्य चेतावनी',
    setAlert: 'चेतावनी सेट करें',
    commodity: 'वस्तु',
    price: 'मूल्य',
    trend: 'रुझान',
    market: 'बाजार',
    state: 'राज्य',
    quantity: 'मात्रा',
    noData: 'बाजार डेटा उपलब्ध नहीं',
    alertWhen: 'जब मूल्य',
    goesAbove: 'से ऊपर जाए',
    goesBelow: 'से नीचे जाए',
    addAlert: 'चेतावनी जोड़ें',
    activeAlerts: 'सक्रिय चेतावनी',
    alertHistory: 'चेतावनी इतिहास',
    noAlerts: 'कोई चेतावनी सेट नहीं',
    acknowledge: 'स्वीकार करें',
  },
  crop: {
    title: 'फसल जानकारी',
    search: 'फसल खोजें...',
    season: 'मौसम',
    soilType: 'मिट्टी का प्रकार',
    duration: 'अवधि',
    temperature: 'तापमान',
    rainfall: 'वर्षा',
    varieties: 'किस्में',
    practices: 'सर्वोत्तम अभ्यास',
    noData: 'कोई फसल नहीं मिली',
  },
  disease: {
    title: 'रोग पहचान',
    upload: 'फोटो अपलोड करें',
    analyze: 'विश्लेषण',
    analyzing: 'विश्लेषण हो रहा है...',
    results: 'परिणाम',
    symptoms: 'लक्षण',
    causes: 'कारण',
    treatment: 'उपचार',
    prevention: 'बचाव',
    confidence: 'विश्वसनीयता',
    severity: 'गंभीरता',
    noPhoto: 'शुरू करने के लिए फोटो लें या चुनें',
  },
  community: {
    title: 'समुदाय',
    newPost: 'नई पोस्ट',
    replies: 'जवाब',
    reply: 'जवाब दें',
    writeReply: 'अपना जवाब लिखें...',
    solved: 'हल हो गया',
    markSolved: 'हल के रूप में चिह्नित करें',
    delete: 'हटाएं',
    search: 'पोस्ट खोजें...',
    category: 'श्रेणी',
    urgency: 'आवश्यकता',
    noPosts: 'अभी तक कोई पोस्ट नहीं',
    beFirst: 'पहली पोस्ट करने वाले बनें!',
  },
  schemes: {
    title: 'सरकारी योजनाएं',
    search: 'योजना खोजें...',
    category: 'श्रेणी',
    benefits: 'लाभ',
    eligibility: 'पात्रता',
    documents: 'आवश्यक दस्तावेज',
    apply: 'आवेदन प्रक्रिया',
    website: 'आधिकारिक वेबसाइट',
    helpline: 'हेल्पलाइन',
    noData: 'कोई योजना नहीं मिली',
  },
  soil: {
    title: 'मिट्टी परीक्षण',
    newTest: 'नया परीक्षण',
    ph: 'pH स्तर',
    nitrogen: 'नाइट्रोजन',
    phosphorus: 'फास्फोरस',
    potassium: 'पोटैशियम',
    organicCarbon: 'जैविक कार्बन',
    health: 'मिट्टी स्वास्थ्य',
    recommendations: 'सुझाव',
    history: 'परीक्षण इतिहास',
    noTests: 'अभी तक कोई परीक्षण नहीं',
    optimal: 'आदर्श',
    low: 'कम',
    high: 'उच्च',
    excellent: 'उत्कृष्ट',
    good: 'अच्छा',
    needsImprovement: 'सुधार आवश्यक',
  },
  calendar: {
    title: 'फसल कैलेंडर',
    today: 'आज',
    month: 'महीना',
    addEvent: 'ईवेंट जोड़ें',
    editEvent: 'ईवेंट संपादित करें',
    activity: 'गतिविधि',
    crop: 'फसल',
    date: 'तारीख',
    status: 'स्थिति',
    done: 'पूर्ण',
    pending: 'लंबित',
    missed: 'छूट गया',
    noEvents: 'कोई ईवेंट नियोजित नहीं',
  },
  schemesData: {
    pmKisan: {
      name: 'PM-KISAN',
      ministry: 'कृषि मंत्रालय',
      benefit: 'किसान परिवारों को ₹6,000/वर्ष आय सहायता',
      eligibility: 'सभी भूमिधारक किसान परिवार',
      docs: 'आधार कार्ड, भूमि रिकॉर्ड, बैंक खाता',
    },
    soilHealth: {
      name: 'मृदा स्वास्थ्य कार्ड योजना',
      ministry: 'कृषि मंत्रालय',
      benefit: 'मुफ्त मिट्टी परीक्षण और पोषक तत्व सिफारिशें',
      eligibility: 'सभी किसान',
      docs: 'भूमि रिकॉर्ड, किसान आईडी',
    },
    pmfby: {
      name: 'प्रधानमंत्री फसल बीमा योजना',
      ministry: 'कृषि मंत्रालय',
      benefit: 'कम प्रीमियम पर फसल बीमा',
      eligibility: 'अधिसूचित फसलें उगाने वाले सभी किसान',
      docs: 'भूमि रिकॉर्ड, बैंक विवरण, फसल विवरण',
    },
    kcc: {
      name: 'किसान क्रेडिट कार्ड',
      ministry: 'वित्त मंत्रालय',
      benefit: '4% ब्याज पर ₹3 लाख तक अल्पकालिक फसल ऋण',
      eligibility: 'सभी किसान, बटाईदार, किरायेदार किसान',
      docs: 'भूमि रिकॉर्ड, पहचान प्रमाण, पासपोर्ट फोटो',
    },
    pmfme: {
      name: 'PM सूक्ष्म खाद्य प्रसंस्करण उद्यम योजना',
      ministry: 'खाद्य प्रसंस्करण मंत्रालय',
      benefit: '₹10 लाख तक क्रेडिट-लिंक्ड सब्सिडी',
      eligibility: 'व्यक्तिगत किसान, SHG, FPO',
      docs: 'प्रोजेक्ट रिपोर्ट, पहचान प्रमाण, बैंक विवरण',
    },
  },
  groups: {
    title: 'किसान समूह',
    search: 'समूह खोजें...',
    create: 'समूह बनाएं',
    join: 'शामिल हों',
    leave: 'छोड़ें',
    members: 'सदस्य',
    posts: 'पोस्ट',
    category: 'श्रेणी',
    noGroups: 'कोई समूह नहीं मिला',
    createFirst: 'पहला समूह बनाएं!',
  },
  messages: {
    title: 'संदेश',
    noConversations: 'अभी तक कोई बातचीत नहीं',
    noMessages: 'अभी तक कोई संदेश नहीं',
    typePlaceholder: 'एक संदेश लिखें...',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
  },
  notifications: {
    title: 'सूचनाएं',
    markAllRead: 'सभी पढ़ी हुई चिह्नित करें',
    noNotifications: 'अभी तक कोई सूचना नहीं',
    filter: {
      all: 'सभी',
      unread: 'अपठित',
      read: 'पढ़ी हुई',
    },
  },
  polls: {
    title: 'पोल',
    create: 'पोल बनाएं',
    vote: 'वोट',
    votes: 'वोट',
    noPolls: 'कोई सक्रिय पोल नहीं',
    remaining: 'शेष',
    category: 'श्रेणी',
  },
  loan: {
    title: 'ऋण कैलकुलेटर',
    amount: 'ऋण राशि (₹)',
    rate: 'ब्याज दर (%)',
    tenure: 'अवधि (महीने)',
    monthlyEMI: 'मासिक EMI',
    totalInterest: 'कुल ब्याज',
    totalAmount: 'कुल राशि',
    loanType: 'ऋण प्रकार',
    calculate: 'गणना करें',
    types: {
      personal: 'व्यक्तिगत ऋण',
      crop: 'फसल ऋण',
      gold: 'स्वर्ण ऋण',
      equipment: 'उपकरण ऋण',
    },
  },
  grievances: {
    title: 'शिकायतें',
    newGrievance: 'नई शिकायत',
    subject: 'विषय',
    description: 'विवरण',
    category: 'श्रेणी',
    status: 'स्थिति',
    pending: 'लंबित',
    resolved: 'हल हो गई',
    rejected: 'अस्वीकृत',
    inProgress: 'प्रगति में',
    noGrievances: 'कोई शिकायत दर्ज नहीं',
    categories: {
      irrigation: 'सिंचाई',
      seeds: 'बीज',
      fertilizer: 'उर्वरक',
      subsidy: 'सब्सिडी',
      electricity: 'बिजली',
      road: 'सड़क पहुंच',
      pricing: 'मूल्य निर्धारण',
      compensation: 'फसल मुआवजा',
      other: 'अन्य',
    },
  },
  tracking: {
    title: 'दैनिक ट्रैकिंग लॉग',
    addEntry: 'प्रविष्टि जोड़ें',
    activity: 'गतिविधि',
    notes: 'नोट्स',
    cropHealth: 'फसल स्वास्थ्य',
    good: 'अच्छा',
    average: 'औसत',
    poor: 'खराब',
    noEntries: 'अभी तक कोई प्रविष्टि नहीं',
    activities: {
      watering: 'पानी देना',
      fertilizing: 'खाद डालना',
      weeding: 'निराई',
      spraying: 'छिड़काव',
      harvesting: 'कटाई',
      planting: 'रोपण',
      other: 'अन्य',
    },
  },
  analytics: {
    title: 'विश्लेषण',
    totalEntries: 'कुल प्रविष्टियां',
    activeCrops: 'सक्रिय फसलें',
    completedTasks: 'पूर्ण कार्य',
    weatherImpact: 'मौसम प्रभाव',
    insights: 'स्मार्ट सुझाव',
    noData: 'अभी पर्याप्त डेटा नहीं',
    recommendations: 'सिफारिशें',
    trends: 'रुझान',
  },
  voice: {
    listening: 'सुन रहा है...',
    tapToSpeak: 'बोलने के लिए टैप करें',
    processing: 'प्रसंस्करण...',
    notSupported: 'इस डिवाइस पर वॉयस समर्थित नहीं है',
    permissionDenied: 'माइक्रोफोन अनुमति अस्वीकृत',
    error: 'वॉयस रिकॉग्निशन त्रुटि',
  },
};

const translations: Record<string, TranslationsDict> = { en, hi };

// ─── Language Provider ─────────────────────────────────────────
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState('hi');

  useEffect(() => {
    (async () => {
      const saved = await storageService.getItem<string>(KEYS.SELECTED_LANGUAGE);
      if (saved) setLanguageState(saved);
    })();
  }, []);

  const setLanguage = useCallback(async (code: string) => {
    setLanguageState(code);
    await storageService.setItem(KEYS.SELECTED_LANGUAGE, code);
  }, []);

  const getNestedValue = useCallback(
    (obj: any, path: string): string | undefined => {
      const parts = path.split('.');
      let current = obj;
      for (const part of parts) {
        if (current == null || typeof current !== 'object') return undefined;
        current = current[part];
      }
      return typeof current === 'string' ? current : undefined;
    },
    []
  );

  const t = useCallback(
    (key: string, fallback?: string): string => {
      // Try current language, fall back to English, then fallback param, then key
      const langData = translations[language] || translations.en;
      let val = getNestedValue(langData, key);
      if (val) return val;
      val = getNestedValue(translations.en, key);
      if (val) return val;
      return fallback || key;
    },
    [language, getNestedValue]
  );

  const tWithVars = useCallback(
    (key: string, vars: Record<string, string | number>, fallback?: string): string => {
      let str = t(key, fallback);
      for (const [k, v] of Object.entries(vars)) {
        str = str.replace(`{{${k}}}`, String(v));
      }
      return str;
    },
    [t]
  );

  const getCurrentLanguage = useCallback(() => {
    return LANGUAGES.find(l => l.code === language) || LANGUAGES[0];
  }, [language]);

  const isRTL = language === 'ur';

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
    tWithVars,
    getCurrentLanguage,
    isRTL,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
